# Generated by Django 4.2.8 on 2023-12-27 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0004_appuser_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='is_staff',
        ),
    ]
